### ISSUE TITLE
使用源码引入的方式有什么特别需要注意的吗？

### ISSUE THREAD

**Issue by xiuxiuing** [eleme/HermesEventBus#11]
使用gradle的方式引入是好的，但是把源码搞到工程中，编译，就不能正常使用了

**Comment by xiuxiuing** [comment]
不跨进程也是好用的，跨了进程之后，找不到Subscribe的事件了      D/EventBus: No subscribers registered for event class java.lang.String

**Comment by Xiaofei-it** [comment]
你怎么拷贝的？工程是什么样子的？原因可能是ClassLoader不一致导致的。

**Comment by xiuxiuing** [comment]
谢谢，找到原因了，源码方式引入的时候，HermesEventBus$Service没有配置，导致跨进程使用不了。

**Comment by Xiaofei-it** [comment]
嗯，那我把这个issue关了。
