### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Jelly0726** [eleme/HermesEventBus#13]
接入hermes-eventbus:0.2.0，在debug模式下安装运行都没有问题，但是正是发布打包安装就报
MainActivity及其超类没有公共方法@Subscribe注释但实际上都按照dome上的使用方式
/***
	 * 订阅 退出登录
	 */
	@Subscribe(threadMode = ThreadMode.MAIN)
	public void onEvent(String type){
		switch (type){
			case "LOGIN_OUT":
				logindb=DBHelper.getInstance(getApplicationContext())
						.getLogin();
				break;
		}
	}

错误信息如下：
12-05 14:00:20.296  9135  9135 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.baima/com.example.baima.MainActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.example.baima.MainActivity and its super classes have no public methods with the @Subscribe annotation
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread.access$900(ActivityThread.java:168)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:150)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5665)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
12-05 14:00:20.296  9135  9135 E AndroidRuntime: Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.example.baima.MainActivity and its super classes have no public methods with the @Subscribe annotation
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at org.greenrobot.eventbus.o.a(Unknown Source)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at org.greenrobot.eventbus.c.a(Unknown Source)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at xiaofei.library.hermeseventbus.HermesEventBus.a(Unknown Source)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at com.example.baima.MainActivity.onCreate(Unknown Source)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6372)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
12-05 14:00:20.296  9135  9135 E AndroidRuntime:        ... 9 more
12-05 14:00:20.297  1008  1460 W ActivityManager:   Force finishing activity com.example.baima/.MainActivity

**Comment by Xiaofei-it** [comment]
你试试把eventbus整个库keep一下，不要混淆。看还会不会报错？

**Comment by Xiaofei-it** [comment]
这个问题看起来好像不是hermes库的问题，是eventbus库被代码混淆后产生的问题。

**Comment by Jelly0726** [comment]
感谢您的 回复，问题已找到，确实是混淆的问题，非常感谢
