### ISSUE TITLE
在注册时报错

### ISSUE THREAD

**Issue by java-war** [eleme/HermesEventBus#14]
HermesEventBus.getDefault().register(this);

org.greenrobot.eventbus.EventBusException: Subscriber class com.jwar.monitor.MainActivity and its super classes have no public methods with the @Subscribe annotation

**Comment by Xiaofei-it** [comment]
HermesEventBus用的是EventBus3.0

你看下EventBus最新的用法，和原来不一样，onEvent方法在新版中一定要加@Subscribe注解。

**Comment by java-war** [comment]
@Xiaofei-it 加了注解的，不起作用！

**Comment by Xiaofei-it** [comment]
能看下你的那个类吗？

要加注解并且是public。这个错不是我的库报的，是eventbus报的。也就是说即使你不用我的库，而只用eventbus，还是会报错。

**Comment by Xiaofei-it** [comment]
后来好了吗？
