### ISSUE TITLE
主app和子app之间的通信，主app不能接收子app事件

### ISSUE THREAD

**Issue by jnshilang** [eleme/HermesEventBus#16]
我在主app里面写的eventbus接收事件，但是子app发过来主app收不到，或者子app就没有发送成功。
主app的接收事件处理
  @Subscribe(threadMode = ThreadMode.MAIN)
    public void helloEventBus(MessageEvent message) {
        text_info.setText(message.name);
        System.out.println("传递过来的数据:--->>>"+message.name);
    }
子app的发送事件
 HermesEventBus.getDefault().post(new MessageEvent("tom","123456"));

事件类都是相同的包名，相同的类名，里面结构体都一样。
package com.cn.wt.eventbus;

/**
 * Created by caitong on 16/12/13.
 */
public class MessageEvent {
    public final String name;
    public final String password;
    public MessageEvent(String name,String password) {
        this.name = name;
        this.password=password;
        System.out.println("我进来发送消息了");
    }
}

**Comment by Xiaofei-it** [comment]
两个app分别是怎么初始化的呢？

Manifest里的HermesService有没有把exported属性设为true？

另外注意，两个app的签名和包名可以不一致，但一定要保证事件类所在的包是一样的（这点你已经做到了），并且不能被代码混淆。
