### ISSUE TITLE
HermesEventBus貌似依赖了V7库，导致项目之前集成了actionbarsherlock后再引入有V7的冲突问题

### ISSUE THREAD

**Issue by ChrisWHL** [eleme/HermesEventBus#17]
我在项目中集成了库之后编译报错：
![image](https://cloud.githubusercontent.com/assets/15625572/21300167/967bf28e-c5dc-11e6-9a40-d43843a8a1f2.png)
我的项目之前集成了actionbarsherlock，引用V7包就会报这个错误，可否把V7的依赖去掉啊？

**Comment by Xiaofei-it** [comment]
ActionBarSherlock已经被废弃了，怎么还在用呢？

**Comment by ChrisWHL** [comment]
没办法啊，项目中涉及到自定义键盘、搜索控件，要改动比较麻烦，这个库必须基于V7么？

**Comment by jp1017** [comment]
> 这个库必须基于V7么？

gradle 可以exclude v7啊,具体使用请google

**Comment by ChrisWHL** [comment]
我试试，感谢
