### ISSUE TITLE
能跨进程传输的数据类型有哪些？

### ISSUE THREAD

**Issue by huxq17** [eleme/HermesEventBus#18]
所有的数据类型都可以么？接口和Context可以么？我试了下，没有成功。

**Comment by Xiaofei-it** [comment]
HermesEventbus是用来发事件的，所以发的事件应该是常规的对象，比如基础数据类型或者model。

接口和Context是不能传输的。如果你想实现进程间回调，可以试试Hermes。Hermes是可以传输接口和上下文的。

**Comment by huxq17** [comment]
目前支持的数据只是通过Gson能转成String的么？是不是没有对序列化的对象进行分别处理，bitmap无法跨进程传输。

**Comment by Xiaofei-it** [comment]
对的。目前都是直接Gson把它转成String。bitmap太大，不应该跨进程传输。

**Comment by Xiaofei-it** [comment]
我们实际的场景中，HermesEventBus已经够用了。
