### ISSUE TITLE
两个App要有相同的包名、类名、方法名？

### ISSUE THREAD

**Issue by wx962464** [eleme/HermesEventBus#2]
step 3: （不同app之间通信)
在app间收发的事件类必须有相同的包名、相同的类名和相同的方法？ 这样似乎限制太多啦，而且这样还能在同一个手机上装这样两个应用吗？

**Comment by Xiaofei-it** [comment]
如果你看Hermes库，你就知道为什么要保持那些名字相同。这是为了在不同app之间查找类，当然可以像Hermes那样给类和方法加注解，这些注解在HermesEventBus里也能work，但为了让用户使用方便，这些就没有在readme里写。
保持包名和方法名相同，在实践中非常简单，只要把类直接复制过去就可以了。
至于你提到的同一个手机能不能装两个应用。应用的包名不同就可以安装了。两个app都可以有相同的包和相同的类。
