### ISSUE TITLE
主进程被强制kill掉，子进程为什么过一会儿会自己重启？

### ISSUE THREAD

**Issue by momoc** [eleme/HermesEventBus#25]
我目前是在尝试试用，但我发现一个问题，我主进程被强制kill掉后，子进程也同时kill掉，但是过会儿两个进程又重启了？
![image](https://cloud.githubusercontent.com/assets/8325226/23147412/a828e2d4-f819-11e6-9192-2219c8a33a14.png)

不知道是不是我使用的不恰当，请大神指教，我非常急……

**Comment by momoc** [comment]
补充一下，我子进程是用的service

**Comment by Xiaofei-it** [comment]
这个问题好像不是我的库引起的啊。。。

你进程有没有保活？

**Comment by momoc** [comment]
不好意思   我的错
