### ISSUE TITLE
打包后清单文件会多出一些权限跟组件的申明

### ISSUE THREAD

**Issue by LiuBeixi** [eleme/HermesEventBus#36]
我在使用HermesEventBus的时候，当我打包之后自己反编译发现清单文件中多了许多权限的增加，还有一个HermesEventBus$Service的申明 ，这个原因直接导致在腾讯手机管家上面报毒了~可能申请了敏感的权限，我从多出的权限推测可能是SYSTEM_ALERT_WINDOW这个原因

**Comment by Xiaofei-it** [comment]
你可以看看HermesEventBus文件夹下的Manifest文件，你觉得哪个可能导致你说的问题？

**Comment by LiuBeixi** [comment]
问题解决了，合并清单文件出现冲突了，感谢提醒！！谢谢！
