### ISSUE TITLE
手动杀死进程时会报NullPointerException

### ISSUE THREAD

**Issue by z-chu** [eleme/HermesEventBus#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'void xiaofei.library.concurrentutils.ObjectCanary.set(java.lang.Object)' on a null object reference
at xiaofei.library.hermeseventbus.HermesEventBus$1.onHermesConnected(HermesEventBus.java:98)
atxiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:283)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1305)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1322)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5546)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by Xiaofei-it** [comment]
请说一下复现场景。
是一个app内还是多个app通信？
进程是怎么被杀死的？用户在任务列表里滑动app杀死的，还是系统在一段时间后自动杀死？
杀死之后进行了什么操作，导致上面异常的抛出？

**Comment by z-chu** [comment]
一个app内，退出应用时手动自杀：
 HermesEventBus.getDefault().destroy();
 android.os.Process.killProcess(android.os.Process.myPid());
System.exit(0);

**Comment by Xiaofei-it** [comment]
然后你是不是在主进程又进行了init？

**Comment by z-chu** [comment]
我在Application的onCreate中init，没作判断，每个进程都init了，这是不对的吗？

**Comment by z-chu** [comment]
之后没有做其他操作

**Comment by Xiaofei-it** [comment]
这种做法是对的。
但有点奇怪。我要查一下。
你后来是不是又打开了那个进程？

**Comment by Xiaofei-it** [comment]
进程尽量不要手动杀死。我当时没考虑手动杀死这种情况。如果你不手动杀死，应该不会出现这种情况。

**Comment by z-chu** [comment]
刚刚发现自杀后，然后其他2个进程会因为这个问题跟着崩了，然后被杀的进程又自己启动了

**Comment by z-chu** [comment]
不自杀不会出现

**Comment by Xiaofei-it** [comment]
有一个workaround，就是你不要手动杀死进程。这样做没有意义。实际使用中很少会用到这种做法。

**Comment by Xiaofei-it** [comment]
我当时设计的思路一个进程只要调用了destroy，之后不能再调用init了。任何init都会抛出NPE。其实那个destroy根本不用调用，我在readme中都没有提到这个函数。

**Comment by z-chu** [comment]
我杀死进程，只是为了释放内存，一旦退出，内存里面直接释放了。网上有为加载WebView的界面开启新进程，在该页面退出之后关闭这个进程，来规避webView内存泄漏的做法。

**Comment by Xiaofei-it** [comment]
这个问题我知道。其实有很多其他workaround。workaround的大意是“可以解决问题，但没有从根本上解决问题的办法”。我不知道你有没有试过其他的workaround。总感觉杀进程太暴力。
不过这个issue我会重视，我会尽量解决。

**Comment by Xiaofei-it** [comment]
我在工程的demo里试了一下，发现杀进程不会有问题。你可以看一下。具体代码在工程的app里。
如果你的工程源码可以公开，那你可以让我看看。
另外，杀进程只需要用一个函数，不需要用两个。System.exit(0)理论上是不会执行的。你可以调试看看，如果执行了，请看下面的问题2。
最后，我说一下我对你遇到的情况的一些疑问。
1、我不清楚进程被杀死后为什么会重启？
2、从崩溃的现象分析，进程重启后，那个进程和原来的那个进程是同一个，并且虚拟机也是同一个，也就是说那个进程根本没有死，却导致了App的恢复，从而导致Application恢复的时候走了init，但因为HermesEventBus仍然是原来那个实例，所以里面的域mApis仍为null，所以那时候就会抛NPE。看看你有没有使用一些统计崩溃的工具，或者有没有设置默认的崩溃Handler？不过某些手机上，崩溃确实会导致app的恢复。
3、基于问题2，我不清楚为什么其他进程会再重启。

**Comment by z-chu** [comment]
重现了NullPointerException ，你可以看一下



z-chu@foxmail.com
 
发件人： Xiaofei
发送时间： 2016-08-25 17:54
收件人： eleme/HermesEventBus
抄送： zchu; Author
主题： Re: [eleme/HermesEventBus] 手动杀死进程时会报NullPointerException (#4)
我在工程的demo里试了一下，发现杀进程不会有问题。你可以看一下。具体代码在工程的app里。
如果你的工程源码可以公开，那你可以让我看看。
另外，杀进程只需要用一个函数，不需要用两个。System.exit(0)理论上是不会执行的。你可以调试看看，如果执行了，请看下面的问题2。
最后，我说一下我对你遇到的情况的一些疑问。
1、我不清楚进程被杀死后为什么会重启？
2、从崩溃的现象分析，进程重启后，那个进程和原来的那个进程是同一个，并且虚拟机也是同一个，也就是说那个进程根本没有死，却导致了App的恢复，从而导致Application恢复的时候走了init，但因为HermesEventBus仍然是原来那个实例，所以里面的域mApis仍为null，所以那时候就会抛NPE。看看你有没有使用一些统计崩溃的工具，或者有没有设置默认的崩溃Handler？不过某些手机上，崩溃确实会导致app的恢复。
3、基于问题2，我不清楚为什么其他进程会再重启。

**Comment by z-chu** [comment]
[请看这里](https://github.com/z-chu/HermesEventBus)

**Comment by Xiaofei-it** [comment]
原因已经查明，我已经在项目代码的注释里写了说明。见[这里](https://github.com/eleme/HermesEventBus/blob/master/hermes-eventbus/src/main/java/xiaofei/library/hermeseventbus/HermesEventBus.java)
针对这个情况，我加了两行代码：如果mApis为空，则new一个。
现在允许在destroy后重新建立连接，这样便解决了NPE崩溃。
至于另一个崩溃，目前不准备改进。这个是使用不规范造成的。当时做Hermes库的时候针对这种情况故意抛了这个异常，提醒用户需要规范使用。具体地说就是，主进程杀死之前，子进程要首先断开连接；或者主进程应该在子进程被杀死之后再被杀死。
