### ISSUE TITLE
我看了源码是用service做的，但是和直接用broadCast来做相比似乎速度没有什么提升

### ISSUE THREAD

**Issue by meanwang** [eleme/HermesEventBus#5]
以下是我的测试数据，每次事件中带有1K bytes的数据，耗时取的是1000次事件的平均值：
机型           broadcast耗时         Hermes耗时
Nexus6          11.83ms                   7.79ms
LG D858         9.21ms                    11.6ms
小米note        5.08ms                    10.77ms
oppo A31      28.66ms                    13.4ms

我看你是在发送事件事件时每次都做了锁和解锁，感觉可能是这里产生了耗时。但service bind成功之后已经是同步接口了，感觉多线程的情况才需要做锁或者synchronized。
请问基于什么考虑做锁呢？

**Comment by Xiaofei-it** [comment]
谢谢你的建议，我会进行优化。
加锁是为了防止一些极端情况，比如：连接是需要时间的，很多时候在连接成功之前就已经开始发事件了，这个时候为了保证事件能发出去，所以进行了加锁。

**Comment by meanwang** [comment]
我自己也实现了一个，在service绑定之前是会放入预发送队列，等待connected之后从预发送队列里取出来发送。然后给队列操作加上synchronized，可以保证线程安全，速度也快不少。

**Comment by Xiaofei-it** [comment]
我已经改了一部分代码，希望你再测一下。
但里面有一些小问题，我已经在HermesEventBus类的todo里写了。以后会进行改进。

**Comment by Xiaofei-it** [comment]
我在源码的todo里提到的小问题已经修复，v0.2.0已经发布。

**Comment by meanwang** [comment]
赞~

**Comment by Xiaofei-it** [comment]
能不能再测一下你之前提供的benchmark，看看性能有没有提升？

**Comment by meanwang** [comment]
ok   白天的时候比较忙，晚点我找几部机器测试下

**Comment by meanwang** [comment]
机型 broadcast耗时 Hermes耗时
Nexus6 11.83ms 7.59ms
小米note 5.08ms 10.07ms

找了两部机器测试了下，数据如上，还是会比较慢。

这里奉上我的测试代码：


序列化和反序列化：
`package xiaofei.library.hermeseventbustest;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

public class SerializableUtil {

    public static <T> T toObject(byte[] source) {
        if (null == source) {
            return null;
        }
        ByteArrayInputStream bis = new ByteArrayInputStream(source);
        ObjectInput in = null;
        try {
            in = new ObjectInputStream(bis);
            return (T) in.readObject();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                bis.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            try {
                if (in != null) {
                    in.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return null;
    }

    public static byte[] toByteArray(Object object) {
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        ObjectOutputStream objectOutputStream = null;
        try {
            objectOutputStream = new ObjectOutputStream(byteArrayOutputStream);
            objectOutputStream.writeObject(object);
            return byteArrayOutputStream.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (objectOutputStream != null) {
                    objectOutputStream.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
            try {
                byteArrayOutputStream.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return null;
    }
}
`

BaseEvent：
`package xiaofei.library.hermeseventbustest;

import java.io.Serializable;

/**
 * Created by meanwang on 2016/8/25.
 */
public class BaseEvent implements Serializable {
    public long createTime;
    public byte[] data;
}
`

postEvent代码：
`findViewById(R.id.post_event).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                for(int i = 0;i < 500;i ++) {
                    BaseEvent baseEvent = new BaseEvent();
                    baseEvent.data = new byte[1024];
                    baseEvent.createTime = System.currentTimeMillis();
                    HermesEventBus.getDefault().post(SerializableUtil.toByteArray(baseEvent));
                }
            }
        });`

统计平均时间的代码：
`private int serviceEventCount = 0;
    private float avgServiceEventCost = 0;
    @Subscribe
    public void baseEvent(byte[] data){
        BaseEvent baseEvent = SerializableUtil.toObject(data);
        Log.e("EventBus","onEvent Called,cost is " + (System.currentTimeMillis() - baseEvent.createTime) + "ms.");
        long cost = (System.currentTimeMillis() - baseEvent.createTime);
        Log.e("InterProcessEventCost", "serviceEvent cost is " + cost + " ms");
        avgServiceEventCost = (avgServiceEventCost * serviceEventCount + cost)/(serviceEventCount + 1);
        serviceEventCount += 1;
        Log.e("InterProcessEventCost", "avgServiceEventCost is " + avgServiceEventCost + " ms,count is " + serviceEventCount);

    }`

对比组中sendBroadcast的代码：
`for (int i = 0; i < 500; i++) {
                            TestReceiverEvent testReceiverEvent = new TestReceiverEvent();
                            testReceiverEvent.createTime = System.currentTimeMillis();
                            testReceiverEvent.data = new byte[1024];
                            Intent intent = new Intent(InterProcessEventReceiver.IntentAction);
                            intent.setPackage(Utils.getPackageName());
                            intent.putExtra(InterProcessEventReceiver.KEY_EVENT_DATA, SerializableUtil.toByteArray(testReceiverEvent));
                            sendBroadcast(intent);
                        }`

**Comment by Xiaofei-it** [comment]
好的，谢谢！
