### ISSUE TITLE
多个APP间通讯的问题

### ISSUE THREAD

**Issue by MHuangXin** [eleme/HermesEventBus#8]
在多个APP之间通讯的时候，在子 APP 中Application调用connect主APP，然后调用post，主APP不能收到该Event，还有主APP如何把事件post给子APP因为主APP是调用init方法的默认使用的EventBus的post了，也就是默认当前进程post，而子app是默认给主APP post想给自己post也没提供方法，我是没用起来

**Comment by MrHuangXin** [comment]
问题找到，因为服务的启动过程达到Connected状态需要一段时间，所以要在Connected之后post才可以；建议在文档中提示这点，还有就是对于Connected和Disconnected的状态要分发给用户知道，不至于误导

**Comment by Xiaofei-it** [comment]
你有没有试过最新版？你可以把你的代码让我看看。
我原理里已经写了。子app把事件传给主app，主app使用eventbus在内部分发事件，之后使用Hermes把事件回传给子app，子app再分发事件。

**Comment by Xiaofei-it** [comment]
你试试最新版需要等待吗？最新版的是这样的：在连接成功之前，如果你post事件，该事件是放队列里，等连接成功后，队列里的事件被一一分发。

**Comment by MrHuangXin** [comment]
嗯好我试试

**Comment by MrHuangXin** [comment]
我今天才down的代码应该是最新的呀

**Comment by Xiaofei-it** [comment]
最新版是0.2.0

**Comment by MrHuangXin** [comment]
![qq 20161114163529](https://cloud.githubusercontent.com/assets/15179354/20258015/653342a0-aa88-11e6-9c51-7f41a082c450.png)
用的0.0.2Connected没有分发事件啊

**Comment by Xiaofei-it** [comment]
你试过了吗？

你先不要看源码，先试试connect之后立马发一个event，你看看之后能不能收到

**Comment by MrHuangXin** [comment]
connect之后是可以的，但是没有像你说的如果post后如果是disconnect是会入队列等待到connect后再分发的

**Comment by Xiaofei-it** [comment]
你可以这样试试

```
HermesEventBus.getDefault().init(this);
HermesEventBus.getDefault().post("Event posted before connection from sub-process");
```

按理说那句话是会被发出去的。

**Comment by Xiaofei-it** [comment]
刚刚那两句代码是说，子进程调用init，那时候其实还没连接成功，但我们还是post事件。在最新版中，这个事件会在连接成功之后被发出。

你试试有没有问题。

**Comment by MrHuangXin** [comment]
我知道这个方法是只兼容了当前App是宿主也就是调了init，并不兼容当前App是子app(connectApp)情况

**Comment by MrHuangXin** [comment]
也就是这样不能发出去
HermesEventBus.getDefault().connectApp(this, "*****”);
HermesEventBus.getDefault().post("Event posted before connection from sub-process");

**Comment by Xiaofei-it** [comment]
你确定吗？我过一阵看看。

**Comment by MrHuangXin** [comment]
ok我再试试，给你回复

**Comment by Xiaofei-it** [comment]
所有逻辑封装在`mRemoteApis`里。

我最近有点忙，具体问题还要过一阵排查。

不过非常感谢你的反馈。
